### ISSUE TITLE
Small typo in setup script

### ISSUE THREAD

**Issue by branchmispredictor** [prabirshrestha/simple-arch-installer#4]
I've been reading through a few folk's install scripts just to pickup tips and tricks, and I saw a typo in your script here: https://github.com/prabirshrestha/simple-arch-installer/blob/master/simple-arch-installer#L125

You probably meant `mountpoint=/var/log` instead of `mountpoint=/var/lib`. Since it's not automountable, it won't impact anything, but if you create a dataset under it, it would

**Comment by prabirshrestha** [comment]
feel free to send a PR.

**Comment by branchmispredictor** [comment]
I was just letting you know in case you're still using this repo, I haven't used this script so I was not affected by this bug
